### ISSUE TITLE
Hello I was trying to test this interesting idea

### ISSUE THREAD

**Issue by wyatt-herkamp** [NickAcPT/Lithium-TestPlugin#1]
`[19:58:21 INFO]: [LithiumTest] Enabling LithiumTest v1.1-BETA
[19:58:21 ERROR]: Error occurred while enabling LithiumTest v1.1-BETA (Is it up to date?)
java.lang.NoClassDefFoundError: net/nickac/lithium/backend/controls/impl/LImage
	at net.nickac.testing.lithium.LithiumTest.onEnable(LithiumTest.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[1.12.1.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [1.12.1.jar:git-Spigot-da42974-8f47214]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: net.nickac.lithium.backend.controls.impl.LImage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[1.12.1.jar:git-Spigot-da42974-8f47214]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[1.12.1.jar:git-Spigot-da42974-8f47214]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 12 more
`
However the test plugin throws a Class Not Found Exception. :(

**Comment by NickAcPT** [comment]
I don't see how that happened. It somehow couldn't find the Lithium Image's class.
Have you downloaded the Release Candidate version of the plugin ?

**Comment by wyatt-herkamp** [comment]
Yes I am using the release candidate.

**Comment by NickAcPT** [comment]
> Yes I am using the release candidate.

I don't know how that error is possible... Does the Lithium plugin load before the test plugin?
I checked the files and the classes are there.

**Comment by wyatt-herkamp** [comment]
Here is the whole log
https://paste.ee/p/qT4n4
My Plugins 
[17:23:12 INFO]: Plugins (10): LuckPerms, QuestRealmsGroups, Lithium, QuestRealmsRewards, Vault, LithiumTest, LearningSpigot, PlaceholderAPI, KingServerInfo, UltraChat
The Plugin LearningSpigot does not have anything in it. And the rest you can find the code or the plugin.

**Comment by yannicklamprecht** [comment]
The log says that you are **not** using the latest version.

https://paste.ee/p/qT4n4#s=0&l=136
https://paste.ee/p/qT4n4#s=0&l=146


Please update to Lithium Beta 1.2 
https://github.com/NickAcPT/Lithium-Spigot/releases/tag/1.2-RC
https://github.com/NickAcPT/Lithium-TestPlugin/releases/tag/1.2-RC

They should work very well. Tested it myself.

**Comment by NickAcPT** [comment]
Closing because it was solved in a private conversation with the issue author. Fix: Performing redownload of the mentioned files.
